annotationinfoservice/datasets/models.py
from sqlalchemy import Column, Integer, String, Float, ForeignKey, ARRAY
from sqlalchemy.orm import relationship
from sqlalchemy.sql.sqltypes import BigInteger
from annotationinfoservice.database import Base


class NamedModel(object):
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False, unique=True)

    def __repr__(self):
        return "{}({})".format(self.name, self.id)

    def __getitem__(self, field):
        return self.__dict__[field]


class DataSet(NamedModel, Base):
    __tablename__ = "dataset"
    image_source = Column(String(200), nullable=False)
    flat_segmentation_source = Column(String(200), nullable=True)
    pychunkgraph_segmentation_source = Column(String(200), nullable=True)
    pychunkgraph_endpoint = Column(String(200), nullable=True)
    annotation_engine_endpoint = Column(String(200), nullable=True)
    synapse_segmentation_source = Column(String(200), nullable=True)
    pychunkedgraph_viewer_source = Column(String(200), nullable=True)
    graphene_source = Column(String(200), nullable=True)
    pychunkedgraph_supervoxel_source = Column(String(200), nullable=True)
    analysis_database_ip = Column(String(100), nullable=True)


class ImageSource(NamedModel, Base):
    __tablename__ = "image_source"
    viewer_layer_name = Column(String(100), nullable=True)
    image_source = Column(String(200), nullable=False)
    description = Column(String(500), nullable=True)
    aligned_volume_id = Column(Integer, ForeignKey("aligned_volume.id"))
    aligned_volume = relationship("AlignedVolume")


class AlignedVolume(NamedModel, Base):
    __tablename__ = "aligned_volume"
    display_name = Column(String(100), nullable=True)
    description = Column(String(500), nullable=True)
    image_source = Column(String(200), nullable=False)
    # base_resolution = Column(ARRAY(Integer,dimensions=1))
    # preferred_stack_id = Column(Integer, ForeignKey('datastack.id'))
    # preferred_stack = relationship("DataStack")


class DataStack(NamedModel, Base):
    __tablename__ = "datastack"
    display_name = Column(String(100), nullable=True)
    viewer_layer_name = Column(String(100), nullable=True)
    aligned_volume_id = Column(Integer, ForeignKey("aligned_volume.id"))
    aligned_volume = relationship("AlignedVolume")
    segmentation_source = Column(String(200), nullable=True)
    skeleton_source = Column(String(200), nullable=True)
    analysis_database = Column(String(100), nullable=True)
    viewer_site = Column(String(200), nullable=True)
    synapse_table = Column(String(100), nullable=True)
    soma_table = Column(String(100), nullable=True)
    proofreading_status_table = Column(String(100), nullable=True)
    cell_identification_table = Column(String(100), nullable=True)
    proofreading_review_table = Column(String(100), nullable=True)
    local_server = Column(String(200), nullable=False)
    description = Column(String(500), nullable=True)
    viewer_resolution_x = Column(Float(), nullable=True)
    viewer_resolution_y = Column(Float(), nullable=True)
    viewer_resolution_z = Column(Float(), nullable=True)
    base_link_id = Column(BigInteger, nullable=True)

annotationinfoservice/datasets/__init__.py
__version___ = "4.3.3"

annotationinfoservice/datasets/controllers.py
# Import flask dependencies
from flask import Blueprint, jsonify, render_template, current_app
from annotationinfoservice.datasets.models import DataSet
from annotationinfoservice.datasets.schemas import DataSetSchema
import neuroglancer

mod_datasets = Blueprint("datasets", __name__, url_prefix="/datasets")

__version__ = "3.17.1"

__version__ = "4.3.3"


@mod_datasets.route("/")
def index():
    datasets = DataSet.query.all()
    return render_template("datasets.html", datasets=datasets, version=__version__)


@mod_datasets.route("/dataset/<datasetname>")
def dataset_view(datasetname):
    dataset = DataSet.query.filter(DataSet.name == datasetname).first_or_404()
    state = neuroglancer.ViewerState()
    state.layers["img"] = neuroglancer.ImageLayer(
        source="precomputed://" + dataset.image_source
    )
    if dataset.pychunkedgraph_viewer_source is not None:
        state.layers["seg"] = neuroglancer.SegmentationLayer(
            source="graphene://" + dataset.pychunkedgraph_viewer_source
        )
    else:
        state.layers["seg"] = neuroglancer.SegmentationLayer(
            source="precomputed://" + dataset.flat_segmentation_source
        )
    state.layers["ann"] = neuroglancer.AnnotationLayer()
    state.layout = "xy-3d"
    ng_url = neuroglancer.to_url(state, prefix=current_app.config["NEUROGLANCER_URL"])
    return render_template(
        "dataset.html", dataset=dataset, ng_url=ng_url, version=__version__
    )


@mod_datasets.route("/api/datasets")
def get_datasets():
    datasets = DataSet.query.all()
    return jsonify([d.name for d in datasets])


@mod_datasets.route("/api/dataset/<dataset>", methods=["GET"])
def get_dataset(dataset):
    dataset = DataSet.query.filter_by(name=dataset).first_or_404()
    schema = DataSetSchema()
    return schema.jsonify(dataset)

annotationinfoservice/datasets/views.py
from flask import jsonify, render_template, current_app, make_response, Blueprint, g
from annotationinfoservice.datasets.service import (
    DataStackService,
    AlignedVolumeService,
)
from annotationinfoservice.datasets.base_spelunker import spelunker_state
from nglui.statebuilder import (
    ImageLayerConfig,
    SegmentationLayerConfig,
    AnnotationLayerConfig,
    StateBuilder,
)
from middle_auth_client import (
    auth_required,
    user_has_permission,
    auth_requires_permission,
)
from caveclient import CAVEclient
import flask
import os
import numpy as np

__version__ = "4.3.3"

views_bp = Blueprint("datastacks", __name__, url_prefix="/datastacks")


@views_bp.route("/")
@auth_required
def index():
    datastacks = DataStackService.get_all()
    datastacks = [
        d
        for d in datastacks
        if user_has_permission("view", d.name, "datastack", ignore_tos=True)
    ]
    return render_template(
        "datastacks.html",
        datastacks=datastacks,
        is_admin=g.auth_user["admin"],
        user=g.auth_user["id"],
        logout_url=os.environ.get("STICKY_AUTH_URL", None) + "/api/v1/logout",
        version=__version__,
    )


@views_bp.route("/version")
def get_version():
    "Get version string"
    return jsonify(__version__)


@views_bp.route("/datastack/<datastackname>")
@auth_requires_permission(
    "view", table_arg="datastackname", resource_namespace="datastack"
)
def datastack_view(datastackname):
    datastack = DataStackService.get_datastack_by_name(datastackname)
    if datastack.viewer_resolution_x is not None:
        resolution = [
            datastack.viewer_resolution_x,
            datastack.viewer_resolution_y,
            datastack.viewer_resolution_z,
        ]
    else:
        resolution = [4, 4, 40]

    client = CAVEclient(
        datastackname,
        auth_token=g.auth_token,
        server_address=os.environ.get("GLOBAL_SERVER", None),
    )
    if datastack.base_link_id is not None:
        base_state = client.state.get_state_json(datastack.base_link_id)
    else:
        base_state = None

    img_layer = ImageLayerConfig(
        name="img",
        source=datastack.aligned_volume.image_source,
        contrast_controls=True,
        black=0.0,
        white=1.0,
    )
    # we want the segmentation layer with our target neuron always on
    seg_layer = SegmentationLayerConfig(
        name="seg", source=datastack.segmentation_source
    )
    ann_layer = AnnotationLayerConfig(name="ann")

    # setup a state builder with this layer pipeline
    sb = StateBuilder(
        [img_layer, seg_layer, ann_layer],
        base_state=base_state,
        resolution=resolution,
        client=client,
    )
    if datastack.segmentation_source.startswith("graphene://"):
        new_source = datastack.segmentation_source.replace(
            "https://", "middleauth+https://"
        )
    else:
        new_source = datastack.segmentation_source

    # seg_layer2 = SegmentationLayerConfig(name="seg", source=new_source)
    # sb2 = StateBuilder(
    #     [img_layer, seg_layer2, ann_layer],
    #     base_state=base_state,
    #     resolution=resolution,
    #     client=client,
    # )
    # ng_url2 = sb2.render_state(return_as="url", url_prefix=site2)

    if datastack.viewer_site is not None:
        site = datastack.viewer_site
    else:
        site = current_app.config["NEUROGLANCER_URL"]
    scaling = (
        np.array(client.chunkedgraph.segmentation_info["scales"][0]["resolution"])
        / client.info.viewer_resolution()
    )

    ctr = (
        np.array(
            client.chunkedgraph.segmentation_info["scales"][0].get(
                "voxel_offset", [0, 0, 0]
            )
        )
        * scaling
        + np.array(client.chunkedgraph.segmentation_info["scales"][0]["size"])
        * scaling
        / 2
    )
    viewer_resolution = client.info.viewer_resolution()
    spelunker_state["dimensions"]["x"][0] = float(viewer_resolution[0])
    spelunker_state["dimensions"]["y"][0] = float(viewer_resolution[1])
    spelunker_state["dimensions"]["z"][0] = float(viewer_resolution[2])
    spelunker_state["position"] = ctr.tolist()
    spelunker_image_source = datastack.aligned_volume.image_source
    if spelunker_image_source.startswith("graphene://"):
        spelunker_image_source = spelunker_image_source.replace(
            "https://", "middleauth+https://"
        )
        spelunker_image_source = spelunker_image_source.replace(
            "graphene://", "precomputed://"
        )

    spelunker_state["layers"][0]["source"] = spelunker_image_source
    spelunker_state["layers"][1]["source"] = new_source

    if datastack.skeleton_source is not None:
        skeleton_source = datastack.skeleton_source.replace(
            "precomputed://https://", "precomputed://middleauth+https://"
        )
        spelunker_state["layers"][1]["source"] = [
            {
                "url": new_source,
                "subsources": {
                    "default": True,
                    "graph": True,
                    "bounds": True,
                    "mesh": True,
                },
                "enableDefaultSubsources": False,
            },
            {
                "url": skeleton_source,
                "subsources": {"default": True},
                "enableDefaultSubsources": False,
            },
        ]

    cave_site = "https://ngl.cave-explorer.org/"
    state_id = client.state.upload_state_json(spelunker_state)
    cave_explorer_url = client.state.build_neuroglancer_url(
        state_id, cave_site
    ).replace("/?json_url=", "#!middleauth+")
    spelunker_site = "https://spelunker.cave-explorer.org/"
    spelunker_url = client.state.build_neuroglancer_url(
        state_id, spelunker_site
    ).replace("/?json_url=", "#!middleauth+")

    ng_url = sb.render_state(return_as="url", url_prefix=site)

    return render_template(
        "datastack.html",
        datastack=datastack,
        is_admin=g.auth_user["admin"],
        ng_url=ng_url,
        cave_explorer_url=cave_explorer_url,
        spelunker_url=spelunker_url,
        version=__version__,
    )

annotationinfoservice/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - AnnotationFrameworkInfoService - v.{{version}}</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <ul><li>
     <a href="{{url_for('datastacks.index')}}">AnnotationFrameworkInfoService - v.{{version}}</a>
  </li>

    <li>
          <a href="{{url_for('datastacks.index')}}">Datastack</a>    
    </li>
    <li>
      <a href="/info/api/doc">API Doc</a>    
    </li>
    
    {% if is_admin %}
    <li>
        <a href="{{ url_for ('admin.index')}}">Admin</a>
    </li>
    {% endif %}


  <!-- {% if user %}

    <li style="float:right">
    user_id: {{user}} <a href="https://{{logout_url}}?{{request.path}}">logout</a>
    </li>
  
  {% endif %} -->
</ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% block content %}{% endblock %}
</section>

annotationinfoservice/templates/dataset.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Dataset:{% endblock %}</h1>
{% endblock %}

{% block content %}
<p>{{dataset.name}}</p>
<a href = {{ng_url}}>viewer link</a><br>
<a href = "{{url_for('Annotation Infoservice_dataset_name_resource', dataset=dataset.name)}}">api description</a>

{% endblock %}

annotationinfoservice/templates/datastack.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Datastack:{% endblock %}</h1>
{% endblock %}

{% block content %}
<p>{{datastack.name}}</p>
<p>
<h4>Description:</h4>
{{datastack.description}}
</p>
<a href={{ng_url}}>viewer link</a><br>
<a href={{cave_explorer_url}}>cave-explorer viewer</a><br>
<a href={{spelunker_url}}>spelunker viewer [beta]</a><br>
<a href="{{url_for('api.Annotation Infoservice_data_stack_name_full_resource', datastack=datastack.name)}}">api
  description</a>
<p>
<table>
  <tr>
    <td>Service Links</td>
  </tr>
  <tr>
    <td><a href="{{datastack.local_server}}/annotation/views/aligned_volume/{{datastack.aligned_volume.name}}">
        Annotation Engine</a></td>
  </tr>
  <tr>
    <td><a href="{{datastack.local_server}}/materialize/views/datastack/{{datastack.name}}">
        Materialization Engine</a>
    </td>
  </tr>
  <tr>
    <td><a href="{{datastack.local_server}}/dash/datastack/{{datastack.name}}">
        Dash Apps</a>
    </td>
  </tr>
  {% if datastack.skeleton_source is not none %}
  <tr>
    <td><a href="{{datastack.local_server}}/tourguide/app/datastack/{{datastack.name}}">
        Tourguide</a>
    </td>
  </tr>
  {% endif %}
  <tr>
    <td>
      <a href="/schema">
        Schema Service</a>
    </td>
  </tr>
</table>
</p>
{% endblock %}

annotationinfoservice/templates/datastacks.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Datastacks:{% endblock %}</h1>
{% endblock %}

{% block content %}
{% for datastack in datastacks %}
<p><a href="{{url_for('datastacks.datastack_view',datastackname=datastack.name)}}">{{datastack.name}}</a></p>
{% endfor %}
{% endblock %}

annotationinfoservice/templates/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}{{title}}{% endblock %}</h1>
{% endblock %}

{% block content %}
<p><a href="{{url_for('datasets.index')}}">Datasets</a></p>

{% endblock %}